
```{r}
library(tidyverse)
library(here)
library(colf)
library(ggthemes)
library(lme4)
library(lmerTest)
library(Metrics)
source(here("helper/run_k_fold.R"))

adult_bd <- read_csv(here("adults/adult_exposure_duration.csv"))
adult_stype <- read_csv(here("adults/adult_stimuli_type.csv"))
```



# Exposure duration 

## Connecting simulation files

```{r}
adult_aligned_eig <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_aligned_eig.csv"))
adult_resnet50_eig <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_eig.csv"))
adult_resnet50_nonoise <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nonoise.csv"))
adult_resnet50_nolearning <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nolearning.csv"))
adult_resnet50_kl <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_kl.csv"))
adult_resnet50_surprisal <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal.csv"))
adult_resnet50_surprisal_missing <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal_missing.csv"))
adult_resnet50_surprisal_missing_b <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal_missing_b.csv"))
adult_resnet50_surprisal_missing_c <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal_missing_c.csv"))
adult_resnet50_surprisal_missing_d <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal_missing_d.csv"))



```


## K-fold results 

```{r}
adult_kfold_aligned_eig = run_all_kfold(sim_data = adult_aligned_eig, behavioral_data = adult_bd)
adult_kfold_resnet50_eig = run_all_kfold(sim_data = adult_resnet50_eig, behavioral_data = adult_bd)
adult_kfold_resnet50_nonoise = run_all_kfold(sim_data = adult_resnet50_nonoise, behavioral_data = adult_bd)
adult_kfold_resnet50_nolearning = run_all_kfold(sim_data = adult_resnet50_nolearning, behavioral_data = adult_bd)
adult_kfold_resnet50_kl = run_all_kfold(sim_data = adult_resnet50_kl, behavioral_data = adult_bd)
# first surprisal has some missing parameters, so ran twice
adult_kfold_resnet50_surprisal = run_all_kfold(sim_data = adult_resnet50_surprisal, behavioral_data = adult_bd)
adult_kfold_resnet50_surprisal_missing = run_all_kfold(sim_data = adult_resnet50_surprisal_missing, behavioral_data = adult_bd)
adult_kfold_resnet50_surprisal_missing_b = run_all_kfold(sim_data = adult_resnet50_surprisal_missing_b, behavioral_data = adult_bd)
adult_kfold_resnet50_surprisal_missing_c = run_all_kfold(sim_data = adult_resnet50_surprisal_missing_c, behavioral_data = adult_bd)
adult_kfold_resnet50_surprisal_missing_d = run_all_kfold(sim_data = adult_resnet50_surprisal_missing_d, behavioral_data = adult_bd)


first_pass_surprisal <- adult_kfold_resnet50_surprisal %>% 
  filter(!is.na(mean_rsquared))
second_pass_surprisal <- adult_kfold_resnet50_surprisal_missing %>% 
  filter(!is.na(mean_rsquared))
third_pass_surprisal <- adult_kfold_resnet50_surprisal_missing_b %>% 
  filter(!is.na(mean_rsquared))
fourth_pass_surprisal <- adult_kfold_resnet50_surprisal_missing_c %>% 
  filter(!is.na(mean_rsquared))
fifth_pass_surprisal <- adult_kfold_resnet50_surprisal_missing_d %>% 
  filter(!is.na(mean_rsquared))
current_adult_kfold_resnet50_surprisal <- bind_rows(first_pass_surprisal, second_pass_surprisal, third_pass_surprisal, fourth_pass_surprisal, fifth_pass_surprisal) 


# reorganize other surprisal files 
adult_resnet50_surprisal<- adult_resnet50_surprisal %>% filter(param_id %in% first_pass_surprisal$param_id)
adult_resnet50_surprisal_missing <- adult_resnet50_surprisal_missing %>% filter(param_id %in% second_pass_surprisal$param_id)
adult_resnet50_surprisal_missing_b <- adult_resnet50_surprisal_missing_b %>% filter(param_id %in% third_pass_surprisal$param_id)
adult_resnet50_surprisal_missing_c <- adult_resnet50_surprisal_missing_c %>% filter(param_id %in% fourth_pass_surprisal$param_id)
adult_resnet50_surprisal_missing_d <- adult_resnet50_surprisal_missing_d %>% filter(param_id %in% fifth_pass_surprisal$param_id)
linked_resnet50_full_surprisal <- bind_rows(adult_resnet50_surprisal, adult_resnet50_surprisal_missing, adult_resnet50_surprisal_missing_b, adult_resnet50_surprisal_missing_c, adult_resnet50_surprisal_missing_d)
linked_resnet50_full_surprisal %>% write_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_full_surprisal.csv"))


saveRDS(adult_kfold_aligned_eig, here("cached_data/adult_kfold_aligned_eig.Rds"))
saveRDS(adult_kfold_resnet50_eig, here("cached_data/adult_kfold_resnet50_eig.Rds"))
saveRDS(adult_kfold_resnet50_nonoise, here("cached_data/adult_kfold_resnet50_nonoise.Rds"))
saveRDS(adult_kfold_resnet50_nolearning, here("cached_data/adult_kfold_resnet50_nolearning.Rds"))
saveRDS(adult_kfold_resnet50_kl, here("cached_data/adult_kfold_resnet50_kl.Rds"))
saveRDS(current_adult_kfold_resnet50_surprisal, here("cached_data/adult_kfold_resnet50_surprisal.Rds"))

```



## Full data results 

```{r}
adult_fulldata_aligned_eig = run_all_full_data_fit(sim_data = adult_aligned_eig, behavioral_data = adult_bd)
adult_fulldata_resnet50_eig = run_all_full_data_fit(sim_data = adult_resnet50_eig, behavioral_data = adult_bd)
adult_fulldata_resnet50_nonoise = run_all_full_data_fit(sim_data = adult_resnet50_nonoise, behavioral_data = adult_bd)
adult_fulldata_resnet50_nolearning = run_all_full_data_fit(sim_data = adult_resnet50_nolearning, behavioral_data = adult_bd)
adult_fulldata_resnet50_kl = run_all_full_data_fit(sim_data = adult_resnet50_kl, behavioral_data = adult_bd)

adult_fulldata_resnet50_surprisal = run_all_kfold(sim_data = adult_resnet50_surprisal, behavioral_data = adult_bd)
adult_fulldata_resnet50_surprisal_missing = run_all_kfold(sim_data = adult_resnet50_surprisal_missing, behavioral_data = adult_bd)
first_pass_surprisal <- adult_fulldata_resnet50_surprisal %>% 
  filter(!is.na(mean_rsquared))
second_pass_surprisal <- adult_fulldata_resnet50_surprisal_missing %>% 
  filter(!is.na(mean_rsquared))
adult_fulldata_resnet50_surprisal <- bind_rows(first_pass_surprisal, second_pass_surprisal) 

saveRDS(adult_fulldata_aligned_eig, here("cached_data/adult_fulldata_aligned_eig.Rds"))
saveRDS(adult_fulldata_resnet50_eig, here("cached_data/adult_fulldata_resnet50_eig.Rds"))
saveRDS(adult_fulldata_resnet50_nonoise, here("cached_data/adult_fulldata_resnet50_nonoise.Rds"))
saveRDS(adult_fulldata_resnet50_nolearning, here("cached_data/adult_fulldata_resnet50_nolearning.Rds"))
saveRDS(adult_fulldata_resnet50_kl, here("cached_data/adult_fulldata_resnet50_kl.Rds"))
saveRDS(adult_fulldata_resnet50_surprisal,  here("cached_data/adult_fulldata_resnet50_surprisal.Rds"))
```


# Stimuli type experiment 

```{r}
adult_linked_generalization <- read_csv(here("simulations/sim_adult_stimulus_type/01_linked_sim/linked_adult_stimulus_type.csv"))


adult_stype_behavior_data <- adult_stype %>% 
  mutate(trial_type = case_when(
      trial_type == "deviant" ~ violation_type,
      TRUE ~ "fam" )) %>% 
  mutate(trial_type = if_else(trial_type == "background", "fam", trial_type)) %>% 
    group_by( trial_type, trial_number) %>% 
    summarise(mean_lt = mean(total_rt), 
              count = n(),
              #ssd = sum((20-1) * (sample_n_std ** 2)),
              #sd_sample = (ssd / 20 * count - count) ** .5, 
              sd_lt = sd(total_rt),
              ub_lt = mean_lt + 1.96 * (sd_lt /(count ** .5)),
              lb_lt = mean_lt - 1.96 * (sd_lt /(count ** .5))) 
  
summarized_behavioral_experiment <- adult_stype


data_to_fit <- adult_linked_generalization %>% 
  left_join(adult_stype_behavior_data, by = c("trial_type", "trial_number"))


fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = data_to_fit, lower = c(-Inf, 0.0000001))
sample_slope = fitted_stats$coefficients["param_mean_sample"]
sample_intercept = fitted_stats$coefficients["param_X.Intercept."]
  
scaled_data <- data_to_fit %>% 
    mutate(scaled_samples = mean_sample * sample_slope  + sample_intercept, 
           scaled_ub_sample = ub_sample * sample_slope + sample_intercept, 
           scaled_lb_sample = lb_sample * sample_slope + sample_intercept)

scaled_data %>% saveRDS(here("cached_data/scaled_adults_stim_type.Rds"))
  
rsquared <- cor(scaled_data$mean_lt, scaled_data$scaled_samples)^2
rmse <- rmse(scaled_data$mean_lt, scaled_data$scaled_samples)
```


# Try plotting 

## get the behavioral plots 

```{r}

model_d <- adult_bd %>% 
  mutate(is_first_trial = (trial_number == 1)) %>% 
  mutate(block_id = block_id + 1)


model <- lmer(log(total_rt) ~ trial_number + is_first_trial + trial_number * trial_type + log(block_id) + (1 | prolific_id) , data = model_d)

new_data <- adult_bd %>% 
  mutate(is_first_trial = trial_number == 1) %>% 
  mutate(block_id = block_id + 1) %>%
  distinct(trial_number, is_first_trial, trial_type, block_id) %>% 
  mutate(prolific_id = 1)

new_data$pred = stats::predict(model, re.form = NA, newdata = new_data) 

new_data <- new_data %>% 
 ungroup() %>% 
  group_by(trial_type, trial_number) %>% 
  tidyboot::tidyboot_mean(pred, na.rm=T) %>% 
  mutate(pred = empirical_stat, 
        pred_lb = ci_lower, 
         pred_ub = ci_upper)


bp <- adult_bd %>% 
  ggplot(aes(x = trial_number, y = log(total_rt), color = trial_type)) + 
  stat_summary(fun.data = "mean_cl_boot") + 
  #geom_ribbon(data = new_data, aes(x = trial_number, y = pred, ymin = pred_lb, ymax = pred_ub, fill = trial_type, group = trial_type, alpha = .1), colour = NA) + 
  geom_line(data = new_data, aes(x = trial_number, y = pred, color = trial_type, group = trial_type)) + 
  theme_few()  + 
  theme(legend.position = "none") + 
  ylab("Log-transformed looking time") + 
  xlab("Trial Number")

```

## collect the best fitting plots


```{r}
adult_kfold_resnet50_eig <- readRDS(here("cached_data/adult_kfold_resnet50_eig.Rds"))
adult_kfold_resnet50_nonoise <- readRDS(here("cached_data/adult_kfold_resnet50_nonoise.Rds"))
adult_kfold_resnet50_nolearning <- readRDS(here("cached_data/adult_kfold_resnet50_nolearning.Rds"))
adult_kfold_resnet50_kl <- readRDS( here("cached_data/adult_kfold_resnet50_kl.Rds"))
adult_kfold_resnet50_surprisal <- readRDS(here("cached_data/adult_kfold_resnet50_surprisal.Rds"))

adult_resnet50_eig <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_eig.csv"))
adult_resnet50_nonoise <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nonoise.csv"))
adult_resnet50_nolearning <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nolearning.csv"))
adult_resnet50_kl <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_kl.csv"))

adult_resnet50_surprisal <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal.csv"))
adult_resnet50_surprisal_missing <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_surprisal_missing.csv"))

# the surprisal needs some further processing 
first_surprisal_complete <- adult_resnet50_surprisal %>% group_by(param_id) %>% count() %>% filter(n == 22) %>% pull(param_id)
second_surprisal_compelte <- adult_resnet50_surprisal_missing %>% group_by(param_id) %>% count() %>% filter(n == 22) %>% pull(param_id)
first_surprisal <- adult_resnet50_surprisal %>% filter(param_id %in% first_surprisal_complete)
second_surprisal <- adult_resnet50_surprisal_missing %>% filter(param_id %in% second_surprisal_compelte)
adult_resnet50_surprisal <- bind_rows(first_surprisal, second_surprisal)


get_best_fit_data <- function(kfold_results, all_fit, behavioral_d, metrics){
  
  # get the best fitting parameters
  if (metrics == "rmse"){
    best_fit_param <- kfold_results %>% 
      arrange(mean_rmse) %>% 
      head(1) %>% 
      pull(param_id)
  }else if(metrics == "rsquared"){
    best_fit_param <- kfold_results %>% 
      arrange(-mean_rsquared) %>% 
      head(1) %>% 
      pull(param_id)
  }
  best_fit <- all_fit %>% filter(param_id == best_fit_param)
  
  # clean the behavioral data to prepare fitting 
  behavioral_d <- summarize_behavioral_data(behavioral_d) %>% ungroup() %>% 
    left_join(best_fit %>% ungroup(), by = c("trial_number", "trial_type")) 
  fitted_stats = colf_nlxb(mean_lt ~ mean_sample, data = behavioral_d, lower = c(-Inf, 0.0000001))
  sample_slope = fitted_stats$coefficients["param_mean_sample"]
  sample_intercept = fitted_stats$coefficients["param_X.Intercept."]
  
  scaled_data <- best_fit %>% 
    mutate(scaled_samples = mean_sample * sample_slope  + sample_intercept, 
           scaled_ub_sample = ub_sample * sample_slope  + sample_intercept, 
           scaled_lb_sample = lb_sample * sample_slope + sample_intercept)
  
  
  return(scaled_data)
}

best_fit_eig <- get_best_fit_data(adult_kfold_resnet50_eig, adult_resnet50_eig, adult_bd, "rsquared") %>% mutate(type = "EIG")
best_fit_kl <-  get_best_fit_data(adult_kfold_resnet50_kl, adult_resnet50_kl, adult_bd, "rsquared") %>% mutate(type = "KL")
best_fit_suprisal <- get_best_fit_data(adult_kfold_resnet50_surprisal, adult_resnet50_surprisal, adult_bd, "rsquared") %>% mutate(type = "Surprisal")
best_fit_nonoise <- get_best_fit_data(adult_kfold_resnet50_nonoise, adult_resnet50_nonoise, adult_bd, "rsquared") %>% mutate(type = "No Noise")
best_fit_nolearning <- get_best_fit_data(adult_kfold_resnet50_nolearning, adult_resnet50_nolearning, adult_bd, "rsquared") %>% mutate(type = "No Learning")


sim_plot <- bind_rows(best_fit_eig, best_fit_kl, best_fit_suprisal, best_fit_nonoise, best_fit_nolearning) %>% 
  mutate(trial_type = if_else(trial_type == "background", "Background", "Deviant")) %>% 
  mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) %>% 
  ggplot(aes(x = trial_number, y = log(scaled_samples), color = trial_type)) + 
  geom_point() + 
  geom_line(aes(group = trial_type)) + 
  theme_few() +
  geom_pointrange(aes(ymin = log(scaled_lb_sample), ymax = log(scaled_ub_sample))) + 
  facet_wrap(~type, scales = "free_y") + 
  theme(
  legend.position = c(0.85, 0.25), # c(0,0) bottom left, c(1,1) top-right.
  legend.background = element_rect(fill = "white", colour = NA) 
) + 
  ylab("") + 
  xlab("") + 
  guides(color=guide_legend(title="Trial Type"))
```

## put things together? 

```{r fig.width=8, fig.height=4}
library(cowplot)
plot_grid(bp, sim_plot, rel_widths = c(1, 2.5))
```

