
```{r}
library(tidyverse)
library(here)
library(lme4)
library(ggthemes)
library(cowplot)
library(colf)
library(Metrics)

source(here("helper/run_k_fold.R"))
source(here("helper/viz_fits.R"))

# reading adult data 
adult_bd <- read_csv(here("adults/adult_exposure_duration.csv"))
adult_resnet50_eig <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_eig.csv"))
adult_resnet50_nonoise <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nonoise.csv"))
adult_resnet50_nolearning <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_nolearning.csv"))
adult_resnet50_kl <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_kl.csv"))
adult_resnet50_surprisal <- read_csv(here("simulations/sim_adult_exposure_duration/01_linked_sim/linked_resnet50_full_surprisal.csv"))

# reading infant data
infant_data = read_csv(here('infants/data/infant_exposure_duration.csv')) %>% filter(fam_or_test == 'test', !exclude)
infant_data = infant_data %>% mutate(subj_id = paste0(experiment, subject_num))
grouped_infant_means = infant_data %>% group_by(test_type, fam_duration) %>% dplyr::summarize(LT = mean(LT))



infant_resnet50_eig = read_csv(here('simulations/sim_infant_exposure_duration/01_linked_sim/linked_resnet50_eig.csv')) 
infant_resnet50_nonoise = read_csv(here('simulations/sim_infant_exposure_duration/01_linked_sim/linked_resnet50_nonoise.csv'))
infant_resnet50_nolearning = read_csv(here('simulations/sim_infant_exposure_duration/01_linked_sim/linked_resnet50_nolearning.csv'))
infant_resnet50_kl = read_csv(here('simulations/sim_infant_exposure_duration/01_linked_sim/linked_resnet50_KL.csv'))
infant_resnet50_surprisal = read_csv(here('simulations/sim_infant_exposure_duration/01_linked_sim/linked_resnet50_surprisal_short.csv'))

```


# Scaling the simulation for plotting 

```{r}
scaled_adult_resnet50_eig <- scale_all_adult_sim(sim_data = adult_resnet50_eig, raw_d = adult_bd)
scaled_adult_resnet50_kl <- scale_all_adult_sim(sim_data = adult_resnet50_kl, raw_d = adult_bd)
scaled_adult_resnet50_surprisal <- scale_all_adult_sim(sim_data = adult_resnet50_surprisal, raw_d = adult_bd)
scaled_adult_resnet50_nonoise <- scale_all_adult_sim(sim_data = adult_resnet50_nonoise, raw_d = adult_bd)
scaled_adult_resnet50_nolearning <- scale_all_adult_sim(sim_data = adult_resnet50_nolearning, raw_d = adult_bd)


scaled_infant_resnet50_eig <- scale_all_infant_sim(infant_resnet50_eig, grouped_infant_means)
scaled_infant_resnet50_kl <- scale_all_infant_sim(infant_resnet50_kl, grouped_infant_means)
scaled_infant_resnet50_surprisal <- scale_all_infant_sim(infant_resnet50_surprisal, grouped_infant_means)
scaled_infant_resnet50_nonoise <- scale_all_infant_sim(infant_resnet50_nonoise, grouped_infant_means) # only has 53 param_id
scaled_infant_resnet50_nolearning <- scale_all_infant_sim(infant_resnet50_nolearning, grouped_infant_means)


saveRDS(scaled_adult_resnet50_eig,here("cached_data/scaled_adult_resnet50_eig.Rds"))
saveRDS(scaled_adult_resnet50_kl, here("cached_data/scaled_adult_resnet50_kl.Rds"))
saveRDS(scaled_adult_resnet50_surprisal,here("cached_data/scaled_adult_resnet50_surprisal.Rds"))
saveRDS(scaled_adult_resnet50_nonoise,here("cached_data/scaled_adult_resnet50_nonoise.Rds"))
saveRDS(scaled_adult_resnet50_nolearning,here("cached_data/scaled_adult_resnet50_nolearning.Rds"))


saveRDS(scaled_infant_resnet50_eig,here("cached_data/scaled_infant_resnet50_eig.Rds"))
saveRDS(scaled_infant_resnet50_kl, here("cached_data/scaled_infant_resnet50_kl.Rds"))
saveRDS(scaled_infant_resnet50_surprisal,here("cached_data/scaled_infant_resnet50_surprisal.Rds"))
saveRDS(scaled_infant_resnet50_nonoise,here("cached_data/scaled_infant_resnet50_nonoise.Rds"))
saveRDS(scaled_infant_resnet50_nolearning,here("cached_data/scaled_infant_resnet50_nolearning.Rds"))


```



# Reading all the scaled things 

```{r}
scaled_adult_resnet50_eig <- readRDS(here("cached_data/scaled_adult_resnet50_eig.Rds"))
scaled_adult_resnet50_kl <- readRDS(here("cached_data/scaled_adult_resnet50_kl.Rds"))
scaled_adult_resnet50_surprisal <- readRDS(here("cached_data/scaled_adult_resnet50_surprisal.Rds"))
scaled_adult_resnet50_nonoise <- readRDS(here("cached_data/scaled_adult_resnet50_nonoise.Rds"))
scaled_adult_resnet50_nolearning <- readRDS(here("cached_data/scaled_adult_resnet50_nolearning.Rds"))

scaled_infant_resnet50_eig <- readRDS(here("cached_data/scaled_infant_resnet50_eig.Rds"))
scaled_infant_resnet50_kl <- readRDS(here("cached_data/scaled_infant_resnet50_kl.Rds"))
scaled_infant_resnet50_surprisal <- readRDS(here("cached_data/scaled_infant_resnet50_surprisal.Rds"))
scaled_infant_resnet50_nonoise <- readRDS(here("cached_data/scaled_infant_resnet50_nonoise.Rds"))
scaled_infant_resnet50_nolearning <- readRDS(here("cached_data/scaled_infant_resnet50_nolearning.Rds"))
```



# Plotting behaviors!

## side by side comparison

```{r}
d <- bind_rows(adult_bd |> 
                 rename(x = trial_number,
                        y = total_rt, 
                        tt = trial_type) |>
                 mutate(group = "Adults", 
                        y = y / 1000, 
                        tt = ifelse(tt == "background", 
                                    "Familiar", "Novel")), 
               infant_data |> 
                 rename(x = fam_duration, 
                        y = LT, 
                        tt = test_type) |>
                 mutate(group = "Infants (7 - 9 months)", 
                        y = y, 
                        tt = ifelse(tt == "fam", "Familiar", 
                                    "Novel")))

d %>% 
  ggplot(aes(x=x, y=y, group=tt, color = tt)) + 
  stat_summary(fun.data = "mean_cl_boot",
               geom = "pointrange",
               position = position_dodge(width = .3)) +
  stat_summary(geom = "line",
               position = position_dodge(width = .3)) +
  # geom_smooth(method = "loess") + 
  facet_wrap(~group, scale = "free_y") + 
  theme_few() + 
  scale_y_log10() + 
  ylab("Looking time (s)") +
  xlab("Trial Number") + 
  ggthemes::scale_color_solarized(name = "Trial type") +
  theme(legend.position = "bottom")
```

## get adult 

```{r}
adult_bp <- d %>% 
  filter(group == "Adults") %>% 
  ggplot(aes(x=x, y=y, group=tt, color = tt)) + 
  stat_summary(fun.data = "mean_cl_boot",
               geom = "pointrange",
               position = position_dodge(width = .3)) +
  stat_summary(geom = "line",
               position = position_dodge(width = .3)) +
  # geom_smooth(method = "loess") + 
  #facet_wrap(~group, scale = "free_y") + 
  theme_few() + 
  scale_y_log10() + 
  #coord_cartesian(ylim = c(0, 4)) + 
  ylab("Looking time (s)") +
  xlab("Trial Number") + 
  ggthemes::scale_color_solarized(name = "Trial type") +
  theme(legend.position = "none")
```

## get infant

```{r}
infant_bp <- d %>% 
  filter(group == "Infants (7 - 9 months)") %>% 
  ggplot(aes(x=x, y=y, group=tt, color = tt)) + 
  stat_summary(fun.data = "mean_cl_boot",
               geom = "pointrange",
               position = position_dodge(width = .3)) +
  stat_summary(geom = "line",
               position = position_dodge(width = .3)) +
  # geom_smooth(method = "loess") + 
  #facet_wrap(~group, scale = "free_y") + 
  #coord_cartesian(ylim = c(0, 25)) + 
  theme_few() + 
  scale_y_log10() + 
  ylab("Looking time (s)") +
  xlab("Trial Number") + 
  ggthemes::scale_color_solarized(name = "Trial type") +
  theme(legend.position = "none")
```




# Plotting simulation!

```{r}
scaled_adult_resnet50_eig <- scale_all_adult_sim(sim_data = adult_resnet50_eig, raw_d = adult_bd)
scaled_adult_resnet50_kl <- scale_all_adult_sim(sim_data = adult_resnet50_kl, raw_d = adult_bd)
scaled_adult_resnet50_surprisal <- scale_all_adult_sim(sim_data = adult_resnet50_surprisal, raw_d = adult_bd)
scaled_adult_resnet50_nonoise <- scale_all_adult_sim(sim_data = adult_resnet50_nonoise, raw_d = adult_bd)
scaled_adult_resnet50_nolearning <- scale_all_adult_sim(sim_data = adult_resnet50_nolearning, raw_d = adult_bd)


scaled_infant_resnet50_eig <- scale_all_infant_sim(infant_resnet50_eig, grouped_infant_means)
scaled_infant_resnet50_kl <- scale_all_infant_sim(infant_resnet50_kl, grouped_infant_means)
scaled_infant_resnet50_surprisal <- scale_all_infant_sim(infant_resnet50_surprisal, grouped_infant_means)
scaled_infant_resnet50_nonoise <- scale_all_infant_sim(infant_resnet50_nonoise, grouped_infant_means) # only has 53 param_id
scaled_infant_resnet50_nolearning <- scale_all_infant_sim(infant_resnet50_nolearning, grouped_infant_means)

```

## adult simulation 

```{r}
# Create the data frame
data <- data.frame(
  variable = c('a', 'b', 'c', 'd', 'e'),
  mean = c(2.5, 3.0, 4.0, 3.5, 3.8),
  upper_bound = c(3.0, 3.5, 4.5, 4.0, 4.3),
  lower_bound = c(2.0, 2.5, 3.5, 3.0, 3.3)
)

# Calculate the overall mean
overall_mean <- mean(data$mean)

# Calculate standard errors and variances
data$se <- (data$upper_bound - data$lower_bound) / (2 * 1.96)
data$variance <- data$se ^ 2

# Calculate combined variance and overall standard error
combined_variance <- mean(data$variance) / 5
overall_se <- sqrt(combined_variance)

# Calculate confidence interval
ci_lower <- overall_mean - 1.96 * overall_se
ci_upper <- overall_mean + 1.96 * overall_se

# Display results
list(
  overall_mean = overall_mean,
  ci_lower = ci_lower,
  ci_upper = ci_upper
)

```


```{r}
 bind_rows(scaled_adult_resnet50_eig %>% mutate(type = "EIG"),
          scaled_adult_resnet50_kl %>% mutate(type = "KL"), 
          scaled_adult_resnet50_surprisal %>% mutate(type = "Surprisal"), 
          scaled_adult_resnet50_nonoise %>% mutate(type = "No Noise"), 
          scaled_adult_resnet50_nolearning %>% mutate(type = "No Learning")) %>% 
  mutate(trial_type = if_else(trial_type == "background", "Familiar", "Novel")) %>% 
  mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) %>% 
   group_by(
    trial_number, trial_type, type
  ) %>% 
  mutate(
    mean = mean(scaled_samples)
  ) 
  

bind_rows(scaled_adult_resnet50_eig %>% mutate(type = "EIG"),
          scaled_adult_resnet50_kl %>% mutate(type = "KL"), 
          scaled_adult_resnet50_surprisal %>% mutate(type = "Surprisal"), 
          scaled_adult_resnet50_nonoise %>% mutate(type = "No Noise"), 
          scaled_adult_resnet50_nolearning %>% mutate(type = "No Learning")) %>% 
  mutate(trial_type = if_else(trial_type == "background", "Familiar", "Novel")) %>% 
  mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) %>% 
   group_by(
    trial_number, trial_type, type
  ) %>% 
  summarise()
  mutate(se = (scaled_ub - scaled_lb) / (1.96 ** 2), 
         n = count())
```


```{r}

facet_labels <- tibble(
  type = c("EIG","KL","Surprisal", "No Learning", "No Noise"),
  label = c("EIG","KL","Surprisal", "No Learning", "No Noise"), 
  x = c(6, 6, 6, 6, 6), 
  y = c(1, 1, 1, 1, 1),
) %>% mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) 


adult_simulation_summary <- bind_rows(scaled_adult_resnet50_eig %>% mutate(type = "EIG"),
          scaled_adult_resnet50_kl %>% mutate(type = "KL"), 
          scaled_adult_resnet50_surprisal %>% mutate(type = "Surprisal"), 
          scaled_adult_resnet50_nonoise %>% mutate(type = "No Noise"), 
          scaled_adult_resnet50_nolearning %>% mutate(type = "No Learning")) %>% 
  mutate(trial_type = if_else(trial_type == "background", "Familiar", "Novel")) %>% 
  mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) #%>% 
 
  

adult_simulation_plot <- ggplot() +
  theme_few() +
  
  stat_summary(
    data = adult_simulation_summary, 
    aes(x = trial_number, y = scaled_samples/1000, color = trial_type),
    fun.data = mean_cl_boot, na.rm = TRUE)+
   stat_summary(
    data = adult_simulation_summary, 
    aes(x = trial_number, y = scaled_samples/1000, color = trial_type),
    fun.data = mean_cl_boot, na.rm = TRUE, 
    geom = "line") + 

  geom_text(data = facet_labels, aes(x = 6, label = label), y = Inf, vjust = 2)+ 
   scale_y_log10() +
  #coord_cartesian(ylim= c(0, 4)) +
  facet_wrap(~type)+
  theme(
    legend.position = c(0.85, 0.25), # c(0,0) bottom left, c(1,1) top-right.
    legend.background = element_rect(fill = "white", colour = NA) 
  ) + 
  ylab("") + 
  xlab("") + 
  guides(color=guide_legend(title="Trial Type")) + 
  ggthemes::scale_color_solarized(name = "Trial type") + 
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank())


```




## infant simulation

```{r}

facet_labels <- tibble(
  type = c("EIG","KL","Surprisal", "No Learning", "No Noise"),
  label = c("EIG","KL","Surprisal", "No Learning", "No Noise"), 
  x = c(6, 6, 6, 6, 6), 
  y = c(1, 1, 1, 1, 1),
) %>% mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise")))) 


infant_simulation_summary <- bind_rows(scaled_infant_resnet50_eig %>% mutate(type = "EIG"), 
          scaled_infant_resnet50_kl %>% mutate(type = "KL"), 
          scaled_infant_resnet50_surprisal %>% mutate(type = "Surprisal"), 
          scaled_infant_resnet50_nolearning%>% mutate(type = "No Learning"), 
          scaled_infant_resnet50_nonoise %>% mutate(type = "No Noise")) %>%
  mutate(test_type = if_else(test_type == "fam", "Familiar", "Novel")) %>% 
  mutate(across(type, ~factor(., levels=c("EIG","KL","Surprisal", "No Learning", "No Noise"))))


infant_simulation_plot <- ggplot() +
  theme_few() +
  stat_summary(
    data = infant_simulation_summary, 
    aes(x = fam_duration, y = scaled_samples, color = test_type),
    fun.data = mean_cl_boot, na.rm = TRUE)+
   stat_summary(
    data = infant_simulation_summary, 
    aes(x = fam_duration, y = scaled_samples, color = test_type),
    fun.data = mean_cl_boot, na.rm = TRUE, 
    geom = "line") + 
  geom_text(data = facet_labels, aes(x = 5, label = label), y = Inf, vjust = 2)+ 
  #coord_cartesian(ylim= c(0, 25)) +
  scale_y_log10()+ 
  scale_x_continuous(breaks = seq(0, 9, 1)) + 
  facet_wrap(~type)+
  theme(
    legend.position = c(0.85, 0.25), # c(0,0) bottom left, c(1,1) top-right.
    legend.background = element_rect(fill = "white", colour = NA) 
  ) + 
  ylab("") + 
  xlab("") + 
  guides(color=guide_legend(title="Trial Type")) + 
  ggthemes::scale_color_solarized(name = "Trial type") + 
  theme(
  strip.background = element_blank(),
  strip.text.x = element_blank())


```





# Put everything together 

## adult

```{r fig.width=10, fig.height=6}
library(cowplot)
plot_grid(adult_bp, adult_simulation_plot, rel_widths = c(2, 3))
```
```{r fig.width=10, fig.height=6}
plot_grid(infant_bp, infant_simulation_plot, rel_widths = c(2, 3))

```

