
# Load library

```{r}
library(tidyverse)
library(here)

```


# Train Test Data Split 

```{r}
full_d <- read_csv(here("adults/behavioral_data/fake_full.csv"))

# 10% as the train 

train_id <- full_d %>% 
  distinct(prolific_id) %>% 
  pull() %>% 
  sample(round(length(unique(full_d$prolific_id)) * .1))

train_d <- full_d %>% 
  filter(prolific_id %in% train_id)

# 90% as the test 
test_d <- full_d %>% 
  filter(!prolific_id %in% train_id)

write_csv(train_d, here("adults/behavioral_data/fake_train_d.csv"))
write_csv(test_d, here("adults/behavioral_data/fake_test_d.csv"))

```

# Simulation results summarized 

## KL 

```{r}
kl_raw <- read_csv(here("sim_res/00_param_search_raw/kl.csv"))

kl_summarized <- kl_raw %>% 
  rename(stimuli_sequence = stim_sequence) %>% 
  mutate(trial_number = trial_num + 1) %>% 
  mutate(
    param_info = paste("v", v_prior, "ap", alpha_prior, "bp", beta_prior, "weig", weig, "sd_epsilon", sd_epsilon, sep = "_")) %>% 
   group_by(param_info, stimuli_sequence, trial_number, test_type, fam_duration) %>% 
  summarise(
    mean_sample = mean(n_samples)
  ) 

write_csv(kl_summarized, here("sim_res/01_param_search_summarized/kl.csv"))
```

## EIG 

## Suprirsal 

## No noise 

## No learning 





