```{r}
library(tidyverse)
library(ggthemes)
library(here)
source(here("simulations/linking_sim_helper.R"))
```

# sim_adult_exposure_duration

```{r}
linked_folder_path <- "simulations/sim_adult_exposure_duration/01_linked_sim"
trial_info_folder_path <- "simulations/sim_adult_exposure_duration"
unlinked_sim_folder_path <- "simulations/sim_adult_exposure_duration/00_raw_sim"
unlinked_param_info_folder_path <- "simulations/sim_adult_exposure_duration/param_info"
trial_info <- read_csv(here(trial_info_folder_path, "trial_info.csv"))


```

```{r}
unlinked_aligned_eig <- read_csv(here(unlinked_sim_folder_path, "unlinked_aligned_eig.csv"))

unlinked_resnet50_eig <- read_csv(here(unlinked_sim_folder_path, "unlinked_resnet50_eig.csv"))
unlinked_resnet50_nolearning <- read_csv(here(unlinked_sim_folder_path, "unlinked_resnet50_nolearning.csv"))
unlinked_resnet50_nonoise <- read_csv(here(unlinked_sim_folder_path, "unlinked_resnet50_nonoise.csv"))
unlinked_resnet50_kl <- read_csv(here(unlinked_sim_folder_path, "unlinked_resnet50_kl.csv"))
unlinked_resnet50_surprisal <- read_csv(here(unlinked_sim_folder_path, "unlinked_resnet50_surprisal.csv"))
unlinked_resnet50_surprisal_missing <-read_csv(here(unlinked_sim_folder_path,"unlinked_resnet50_surprisal_missingparams.csv"))
unlinked_resnet50_surprisal_missing_b <-read_csv(here(unlinked_sim_folder_path,"unlinked_resnet50_surpirsal_missingparams_b.csv"))
unlinked_resnet50_surprisal_missing_c <-read_csv(here(unlinked_sim_folder_path,"unlinked_resnet50_surpirsal_missingparams_c.csv"))
unlinked_resnet50_surprisal_missing_d <-read_csv(here(unlinked_sim_folder_path,"unlinked_resnet50_surpirsal_missingparams_d.csv"))


unlinked_param_info_resnet50_eig <- read_csv(here(unlinked_param_info_folder_path, "param_info_resnet50_eig.csv"))
unlinked_param_info_resnet50_no_learning <- read_csv(here(unlinked_param_info_folder_path, "param_info_resnet50_no_learning.csv"))
unlinked_param_info_resnet50_no_noise <- read_csv(here(unlinked_param_info_folder_path, "param_info_resnet50_no_noise.csv"))
unlinked_param_info_resnet50_kl <- read_csv(here(unlinked_param_info_folder_path, "param_info_resnet50_kl.csv"))
unlinked_param_info_resnet50_surprisal <- read_csv(here(unlinked_param_info_folder_path, "param_info_resnet50_surprisal.csv"))



linked_aligned_eig <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_eig, 
                                    sim_data = unlinked_aligned_eig)
linked_resnet50_eig <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_eig,
                                    sim_data = unlinked_resnet50_eig)
linked_resnet50_nolearning <-  connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_no_learning, 
                                    sim_data = unlinked_resnet50_nolearning)
linked_resnet50_nonoise<-  connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_no_noise, 
                                    sim_data = unlinked_resnet50_nonoise)
linked_resnet50_kl <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_kl, 
                                    sim_data = unlinked_resnet50_kl)
linked_resnet50_surprisal <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_surprisal, 
                                    sim_data = unlinked_resnet50_surprisal)
linked_resnet50_surprisal_missing <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_surprisal, 
                                    sim_data = unlinked_resnet50_surprisal_missing)
linked_resnet50_surprisal_missing_b <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_surprisal, 
                                    sim_data = unlinked_resnet50_surprisal_missing_b)
linked_resnet50_surprisal_missing_c <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_surprisal, 
                                    sim_data = unlinked_resnet50_surprisal_missing_c)
linked_resnet50_surprisal_missing_d <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_resnet50_surprisal, 
                                    sim_data = unlinked_resnet50_surprisal_missing_d)



# write out the csv
write_csv(linked_aligned_eig, here(linked_folder_path, "linked_aligned_eig.csv"))
write_csv(linked_resnet50_eig, here(linked_folder_path, "linked_resnet50_eig.csv"))
write_csv(linked_resnet50_nolearning, here(linked_folder_path, "linked_resnet50_nolearning.csv"))
write_csv(linked_resnet50_nonoise, here(linked_folder_path, "linked_resnet50_nonoise.csv"))
write_csv(linked_resnet50_kl, here(linked_folder_path, "linked_resnet50_kl.csv"))
write_csv(linked_resnet50_surprisal, here(linked_folder_path, "linked_resnet50_surprisal.csv"))
write_csv(linked_resnet50_surprisal_missing, here(linked_folder_path, "linked_resnet50_surprisal_missing.csv"))
write_csv(linked_resnet50_surprisal_missing_b, here(linked_folder_path, "linked_resnet50_surprisal_missing_b.csv"))
write_csv(linked_resnet50_surprisal_missing_c, here(linked_folder_path, "linked_resnet50_surprisal_missing_c.csv"))
write_csv(linked_resnet50_surprisal_missing_d, here(linked_folder_path, "linked_resnet50_surprisal_missing_d.csv"))



```

# sim_adult_stimulus_type 

```{r}
unlinked_adult_stimulus_type <- read_csv(here("simulations/sim_adult_stimulus_type/00_raw_sim/generalization_downscaled.csv"))
stimulus_type_trial_info <- read_csv(here("simulations/sim_adult_stimulus_type/trial_info.csv"))

linked_adult_stimulus_type <- stimulus_type_trial_info %>% 
    distinct(trial_id, stim_id, fam_duration, violation_type) %>% 
    right_join(unlinked_adult_stimulus_type, by = c("trial_id", "stim_id")) %>% 
    select(param_id, index, fam_duration, violation_type, sample_n_mean, sample_n_std) %>%
    mutate(trial_type = case_when(
      index == fam_duration ~ violation_type,
      TRUE ~ "fam" )) %>% 
  mutate(trial_type = if_else(trial_type == "background", "fam", trial_type)) %>% 
    mutate(trial_number = index + 1) %>% 
    group_by(param_id, trial_type, trial_number) %>% 
    summarise(
      count = n(),
      #ssd = sum((20-1) * (sample_n_std ** 2)),
      #sd_sample = (ssd / 20 * count - count) ** .5, 
      sd_sample = pooled_sd(sample_n_std, 20),
      mean_sample = mean(sample_n_mean), 
      ub_sample = mean_sample + 1.96 * (sd_sample /((400 * count) ** .5)),
      lb_sample = mean_sample - 1.96 * (sd_sample /((400 * count) ** .5)),) %>% # missing SD here!
    ungroup() 
 
linked_adult_stimulus_type %>% write_csv(here("simulations/sim_adult_stimulus_type/01_linked_sim/linked_adult_stimulus_type.csv"))

```



## sanity check

```{r}
linked_resnet50_surprisal_missing_d %>% 
  filter(!is.na(trial_number)) %>% 
  ggplot(aes(x = trial_number, y = mean_sample, color = trial_type)) + 
  stat_summary(fun.data = "mean_cl_boot", position = position_dodge(width = .2))+ 
  theme_few()
```

# relationship between embedding distance and dishabituation magnitude 

## two test 

```{r}
scaledanimals <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_aligned_eig, 
                                    sim_data = read_csv(here(unlinked_sim_folder_path, "unlinked_test_aligned_scaledanimals_eig.csv"))) %>%  
  filter(!is.na(trial_number))

unscaledallstims <- connect_files(trial_info = trial_info, 
                                    param_info = unlinked_param_info_aligned_eig, 
                                    sim_data = read_csv(here(unlinked_sim_folder_path, "unlinked_test_aligned_unscaledallstim_eig.csv"))) %>% 
  filter(!is.na(trial_number))

write_csv(scaledanimals, here(linked_folder_path, "linked_test_scaledanimals.csv"))
write_csv(unscaledallstims, here(linked_folder_path, "linked_test_unscaledallstims.csv"))


bind_rows(
  scaledanimals %>% mutate(type = "scaled animals"), 
  unscaledallstims %>% mutate(type = "unscaled all stim")
) %>% 
  group_by(type, param_id) %>% 
  count()
```

```{r}
bind_rows(
  scaledanimals %>% mutate(type = "scaled animals"), 
  unscaledallstims %>% mutate(type = "unscaled all stim")
) %>% 
ggplot(aes(x = trial_number, y = mean_sample, color = trial_type)) + 
  geom_pointrange(aes(ymin = lb_sample, ymax = ub_sample)) + 
  geom_line() + 
  #geom_line(aes(group = param_id, color = trial_type)) + 
  theme_few()+ 
  facet_grid(param_id~type)
```





relationship between embedding distance and dishabituation magnitude

```{r}
raw_stim_df <- trial_info %>% 
    distinct(trial_id, stim_id, fam_duration, violation_type, .keep_all = TRUE) %>% 
    right_join(unlinked_aligned_unscaledallstims_eig, by = c("trial_id", "stim_id")) %>% 
    #select(param_id, index, fam_duration, violation_type, sample_n_mean, sample_n_std) %>% 
    right_join(unlinked_param_info_aligned_eig, by = c('param_id')) %>%
    mutate(trial_type = case_when(
      violation_type == "background" ~ "background", 
      violation_type == "identity" & (index == fam_duration ) ~ "deviant",
      TRUE ~ "background"))%>% 
    mutate(trial_number = index + 1) %>% 
  select(sample_n_mean, sample_n_std, fam, test, trial_type, violation_type, trial_number)

```

```{r}
index_present <- paste0("0", as.character(seq(13, 40)))

emb_df <- read_csv(here("embeddings/aligned_unscaledallstimuli_distance.csv")) %>% 
 rename("stimulus" = "...1") %>% 
 filter(grepl("adults", stimulus) | grepl(paste(index_present, collapse="|"), stimulus)) %>% 
#select(contains("stimulus")|contains("adults") ) %>% 
  filter(!grepl("pair", stimulus)) 

emb_df <- emb_df %>% 
  select(stimulus, matches(paste(emb_df %>% pull(stimulus), collapse="|"))) 

emb_df %>% 
  arrange(stimulus)

distinct_stimulus_pair <- raw_stim_df %>% 
  distinct(fam, test) %>% 
  filter(fam != test)
```

```{r}
replace_name <- function(x){gsub("_adults", "", x)}

emb_df_lookup <- emb_df %>% 
  mutate(stimulus = gsub("_adults", "", stimulus)) %>% 
  rename_with(~replace_name(.))



get_distance <- function(stim_a_name, stim_b_name,  dist){
  if (stim_a_name  == "" | stim_b_name  == ""){
    return (tibble("val" = NA_real_))
  }else{
    return( 
      tibble("val" = dist %>%
      filter(stimulus == {{stim_b_name}}) %>% 
      select({{stim_a_name}}) %>% 
      pull())
      )
  }
  
}

distinct_stimulus_pair_with_distance <- distinct_stimulus_pair %>% 
  ungroup() %>% 
  mutate(edist = map2_df(.x = distinct_stimulus_pair$fam, 
                        .y = distinct_stimulus_pair$test, 
                        .f = get_distance, emb_df_lookup)) %>% 
  unnest(edist)

```

```{r}

stim_df_with_dist <- raw_stim_df %>% 
  left_join(distinct_stimulus_pair_with_distance %>% rename("dist" = val), 
            by = c("fam", "test")) %>% 
  mutate(dist = if_else(is.na(dist), 0, dist)) 

stim_df_with_dist %>% 
  filter(trial_type != "background") %>% 
  ggplot(aes(x = dist, y = sample_n_mean)) + 
  geom_point(aes(alpha = .3)) + 
  geom_smooth() + 
  facet_wrap(~trial_number)


stim_df_with_dist %>% 
  filter(dist < 1) %>% 
  filter(trial_type != "background") %>% 
  ggplot(aes(x = dist, y = sample_n_mean)) + 
  geom_point(aes(alpha = .3)) + 
  geom_smooth() + 
  facet_wrap(~trial_number)
```

# Infant linking

```{r}
linked_folder_path <- "simulations/sim_infant_stimulus_type/01_linked_sim"
trial_info_folder_path <- "simulations/sim_infant_stimulus_type"
unlinked_sim_folder_path <- "simulations/sim_infant_stimulus_type/00_raw_sim"
unlinked_param_info_folder_path <- "simulations/sim_infant_stimulus_type/param_info"

trial_info <- read_csv(here(trial_info_folder_path, "trial_info.csv"))
unlinked_aligned_eig <- read_csv(here(unlinked_sim_folder_path, "generalization_downscaled.csv")) 
unlinked_param_info_aligned_eig <- read_csv(here(unlinked_param_info_folder_path, "param_info_eig.csv"))

linked_aligned_eig <- connect_files_stim_type(trial_info = trial_info, 
                                    param_info = unlinked_param_info_aligned_eig, sim_data = unlinked_aligned_eig)

write_csv(linked_aligned_eig, here(linked_folder_path, "linked_generalization.csv"))

```


```{r}
read_csv(here("simulations/sim_infant_stimulus_type/01_linked_sim/linked_generalization.csv")) %>% 
  ggplot(aes(x = trial_number, y = mean_sample, color = trial_type)) + 
  geom_point() + 
  geom_line()+
  theme_few()

```

